version: 2
jobs:
  build_and_test:
    docker:
      - image: framgia/laravel-workspace
      - image: mysql:5.7
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DATABASE: forge
          MYSQL_USER: forge
          MYSQL_PASSWORD: 
          MYSQL_ROOT_PASSWORD: 
    steps:
      - checkout
      - run: cp .env.example .env
      # run test
      - run: php artisan key:generate
      - run: php artisan migrate --seed
      - run:
          name: Check PhpUnit
          command: ./vendor/bin/phpunit
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_and_test
